### PR TITLE
feat: adds print button without manually detaching window

### PR DESCRIPTION
**Pull request by JockeCK**
See issue: https://github.com/Neovici/cosmoz-image-viewer/issues/142

### CODE REVIEW

**Comment by cristinecula** [comment]
@JockeCK can't this be implemented without detaching/attaching the window?

**Review by cristinecula — APPROVED** [review]

**Comment by JockeCK** [comment]
> @JockeCK can't this be implemented without detaching/attaching the window?

Not sure, the only way I found was by marking everything to not show up in the printscreen. Did not think that would be very practical.

**Comment by JockeCK** [comment]
I will give it another go, see if I can do some css magic.

**Comment by cristinecula** [comment]
@JockeCK if it performs well enough, you can merge it this way and we'll improve upon it later.

**Pull request merged**
